# Generated by Django 4.0.3 on 2022-03-04 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_alter_game_stations_occupied_at_start'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='game',
            name='video',
        ),
        migrations.AlterField(
            model_name='game',
            name='stations_occupied_at_start',
            field=models.JSONField(default=dict),
        ),
    ]
