# Generated by Django 4.0.3 on 2022-03-04 00:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_remove_game_created_date_remove_game_video_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='video',
            field=models.FileField(null=True, upload_to='videos/%Y/%m/%d/'),
        ),
    ]
