# Generated by Django 4.0.3 on 2022-03-04 00:51

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0004_game_created_date_game_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='round',
            name='player_ids',
        ),
        migrations.AddField(
            model_name='round',
            name='player_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='round',
            name='shots_taken',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='round',
            name='station_number',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.DeleteModel(
            name='Shot',
        ),
    ]
